# Learn more about services, parameters and containers at# http://symfony.com/doc/current/book/service_container.html

parameters:

  ## arguments for Item
  value: 555
  
services:

  ## an item 
  item:
    class: \Tree\Item
    arguments: ['%value%']

  ## a binary tree node
  binarynode:
    class: \Tree\BinaryNode
    arguments: ['@item']
    
  ## a binary tree
  binarytree:
    class: \Tree\BinaryTree